# Generated by Django 4.2.4 on 2024-07-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0031_alter_goodsmodel_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webinfo",
            name="background",
        ),
        migrations.AddField(
            model_name="webinfo",
            name="banner1",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/webinfo/",
                verbose_name="banner1 image",
            ),
        ),
        migrations.AddField(
            model_name="webinfo",
            name="banner2",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/webinfo/",
                verbose_name="banner2 image",
            ),
        ),
        migrations.AddField(
            model_name="webinfo",
            name="banner3",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/webinfo/",
                verbose_name="banner3 image",
            ),
        ),
        migrations.AlterField(
            model_name="webinfo",
            name="logo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/webinfo/",
                verbose_name="logo image",
            ),
        ),
    ]
