# Generated by Django 4.2.4 on 2024-07-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0033_alter_webinfo_address_alter_webinfo_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinfo",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
