# Generated by Django 4.2.4 on 2024-08-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0034_alter_webinfo_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelQR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restaurant",
                    models.CharField(max_length=125, verbose_name="restaurant"),
                ),
                (
                    "room_number",
                    models.CharField(max_length=15, verbose_name="room number"),
                ),
                (
                    "address",
                    models.CharField(max_length=15, verbose_name="room number"),
                ),
                ("qr_code", models.ImageField(blank=True, upload_to="qr_codes/")),
            ],
        ),
    ]
