# Generated by Django 4.2.4 on 2024-08-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0035_hotelqr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotelqr",
            name="restaurant",
        ),
        migrations.AddField(
            model_name="hotelqr",
            name="hotel",
            field=models.CharField(default=1, max_length=125, verbose_name="hotel"),
            preserve_default=False,
        ),
    ]
