# Generated by Django 4.2.4 on 2024-08-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0038_alter_hotelqr_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelqr",
            name="address",
            field=models.CharField(max_length=15, verbose_name="address"),
        ),
    ]
