# Generated by Django 4.2.4 on 2024-08-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0039_alter_hotelqr_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsmodel",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
