# Generated by Django 4.2.4 on 2024-08-20 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0040_goodsmodel_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orderitem",
                to="store.goodsmodel",
            ),
        ),
    ]
